server:
  port: 8100

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8200
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/core
            - JwtFilter
        - id: cart-service
          uri: http://localhost:8400
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/cart
            - JwtFilter
        - id: auth-service
          uri: http://localhost:8300
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/auth
            - JwtFilter

jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g